package edu.uoc.model;

import java.time.OffsetDateTime;

/**
 * Domain model representing a reservation.
 *
 * <p>This entity maps to the {@code reservations} table.</p>
 *
 * <p>Unlike some other domain models, this class is mutable because:</p>
 * <ul>
 *     <li>The database generates {@code reservationId} and {@code createdAt}</li>
 *     <li>Status transitions occur over time (PENDING → CONFIRMED → CANCELLED)</li>
 * </ul>
 *
 * <p>Business rules are enforced in the service layer, not here.</p>
 *
 * @since 1.0
 */
public class Reservation {

    private long reservationId;        // DB-generated
    private long customerId;
    private OffsetDateTime startAt;
    private OffsetDateTime endAt;      // nullable
    private int partySize;
    private String status;
    private String notes;              // nullable
    private OffsetDateTime createdAt;  // DB-generated (read-only for inserts)

    /**
     * Default constructor.
     *
     * <p>Required for certain JDBC and framework patterns.</p>
     */
    public Reservation() {
    }

    /**
     * Creates a new reservation (without ID and createdAt).
     *
     * <p>Used before persisting the reservation in the database.</p>
     *
     * @param customerId customer identifier
     * @param startAt    reservation start date-time
     * @param endAt      reservation end date-time (nullable)
     * @param partySize  number of guests
     * @param status     reservation status
     * @param notes      optional notes (nullable)
     */
    public Reservation(long customerId,
                       OffsetDateTime startAt,
                       OffsetDateTime endAt,
                       int partySize,
                       String status,
                       String notes) {
        this.customerId = customerId;
        this.startAt = startAt;
        this.endAt = endAt;
        this.partySize = partySize;
        this.status = status;
        this.notes = notes;
    }

    public long getReservationId() {
        return reservationId;
    }

    /**
     * Sets the generated reservation ID.
     *
     * <p>This method is intended to be called by the DAO after insertion.</p>
     */
    public void setReservationId(long reservationId) {
        this.reservationId = reservationId;
    }

    public long getCustomerId() {
        return customerId;
    }

    public void setCustomerId(long customerId) {
        this.customerId = customerId;
    }

    public OffsetDateTime getStartAt() {
        return startAt;
    }

    public void setStartAt(OffsetDateTime startAt) {
        this.startAt = startAt;
    }

    public OffsetDateTime getEndAt() {
        return endAt;
    }

    public void setEndAt(OffsetDateTime endAt) {
        this.endAt = endAt;
    }

    public int getPartySize() {
        return partySize;
    }

    public void setPartySize(int partySize) {
        this.partySize = partySize;
    }

    public String getStatus() {
        return status;
    }

    /**
     * Sets reservation status.
     *
     * <p>Status transitions should normally be validated by the service layer.</p>
     */
    public void setStatus(String status) {
        this.status = status;
    }

    public String getNotes() {
        return notes;
    }

    public void setNotes(String notes) {
        this.notes = notes;
    }

    public OffsetDateTime getCreatedAt() {
        return createdAt;
    }

    /**
     * Sets the creation timestamp.
     *
     * <p>This value is generated by the database and populated by the DAO.</p>
     */
    public void setCreatedAt(OffsetDateTime createdAt) {
        this.createdAt = createdAt;
    }
}
